//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSignRemoteService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignRequest", Namespace="https://msign.gov.md")]
    public partial class SignRequest : object
    {
        
        private string ContentDescriptionField;
        
        private MSignRemoteService.ContentType ContentTypeField;
        
        private System.Collections.Generic.List<MSignRemoteService.SignContent> ContentsField;
        
        private MSignRemoteService.ExpectedSigner ExpectedSignerField;
        
        private string ShortContentDescriptionField;
        
        private string SignatureReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ContentDescription
        {
            get
            {
                return this.ContentDescriptionField;
            }
            set
            {
                this.ContentDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MSignRemoteService.ContentType ContentType
        {
            get
            {
                return this.ContentTypeField;
            }
            set
            {
                this.ContentTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<MSignRemoteService.SignContent> Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MSignRemoteService.ExpectedSigner ExpectedSigner
        {
            get
            {
                return this.ExpectedSignerField;
            }
            set
            {
                this.ExpectedSignerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ShortContentDescription
        {
            get
            {
                return this.ShortContentDescriptionField;
            }
            set
            {
                this.ShortContentDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SignatureReason
        {
            get
            {
                return this.SignatureReasonField;
            }
            set
            {
                this.SignatureReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExpectedSigner", Namespace="https://msign.gov.md")]
    public partial class ExpectedSigner : object
    {
        
        private int DelegatedRoleIDField;
        
        private string DelegatorIDField;
        
        private MSignRemoteService.DelegatorType DelegatorTypeField;
        
        private string IDField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public int DelegatedRoleID
        {
            get
            {
                return this.DelegatedRoleIDField;
            }
            set
            {
                this.DelegatedRoleIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DelegatorID
        {
            get
            {
                return this.DelegatorIDField;
            }
            set
            {
                this.DelegatorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public MSignRemoteService.DelegatorType DelegatorType
        {
            get
            {
                return this.DelegatorTypeField;
            }
            set
            {
                this.DelegatorTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentType", Namespace="https://msign.gov.md")]
    public enum ContentType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hash = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pdf = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignContent", Namespace="https://msign.gov.md")]
    public partial class SignContent : object
    {
        
        private byte[] ContentField;
        
        private string CorrelationIDField;
        
        private bool MultipleSignaturesField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrelationID
        {
            get
            {
                return this.CorrelationIDField;
            }
            set
            {
                this.CorrelationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public bool MultipleSignatures
        {
            get
            {
                return this.MultipleSignaturesField;
            }
            set
            {
                this.MultipleSignaturesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DelegatorType", Namespace="https://msign.gov.md")]
    public enum DelegatorType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Person = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Organization = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignResponse", Namespace="https://msign.gov.md")]
    public partial class SignResponse : object
    {
        
        private string MessageField;
        
        private System.Collections.Generic.List<MSignRemoteService.SignResult> ResultsField;
        
        private MSignRemoteService.SignStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<MSignRemoteService.SignResult> Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MSignRemoteService.SignStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignResult", Namespace="https://msign.gov.md")]
    public partial class SignResult : object
    {
        
        private byte[] CertificateField;
        
        private string CorrelationIDField;
        
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrelationID
        {
            get
            {
                return this.CorrelationIDField;
            }
            set
            {
                this.CorrelationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SignStatus", Namespace="https://msign.gov.md")]
    public enum SignStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Expired = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationRequest", Namespace="https://msign.gov.md")]
    public partial class VerificationRequest : object
    {
        
        private System.Collections.Generic.List<MSignRemoteService.VerificationContent> ContentsField;
        
        private string LanguageField;
        
        private MSignRemoteService.ContentType SignedContentTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<MSignRemoteService.VerificationContent> Contents
        {
            get
            {
                return this.ContentsField;
            }
            set
            {
                this.ContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public MSignRemoteService.ContentType SignedContentType
        {
            get
            {
                return this.SignedContentTypeField;
            }
            set
            {
                this.SignedContentTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationContent", Namespace="https://msign.gov.md")]
    public partial class VerificationContent : object
    {
        
        private byte[] ContentField;
        
        private string CorrelationIDField;
        
        private byte[] SignatureField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public byte[] Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrelationID
        {
            get
            {
                return this.CorrelationIDField;
            }
            set
            {
                this.CorrelationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Signature
        {
            get
            {
                return this.SignatureField;
            }
            set
            {
                this.SignatureField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationResponse", Namespace="https://msign.gov.md")]
    public partial class VerificationResponse : object
    {
        
        private System.Collections.Generic.List<MSignRemoteService.VerificationResult> ResultsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Collections.Generic.List<MSignRemoteService.VerificationResult> Results
        {
            get
            {
                return this.ResultsField;
            }
            set
            {
                this.ResultsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationResult", Namespace="https://msign.gov.md")]
    public partial class VerificationResult : object
    {
        
        private System.Collections.Generic.List<MSignRemoteService.VerificationCertificate> CertificatesField;
        
        private string CorrelationIDField;
        
        private string MessageField;
        
        private bool SignaturesValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<MSignRemoteService.VerificationCertificate> Certificates
        {
            get
            {
                return this.CertificatesField;
            }
            set
            {
                this.CertificatesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CorrelationID
        {
            get
            {
                return this.CorrelationIDField;
            }
            set
            {
                this.CorrelationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SignaturesValid
        {
            get
            {
                return this.SignaturesValidField;
            }
            set
            {
                this.SignaturesValidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VerificationCertificate", Namespace="https://msign.gov.md")]
    public partial class VerificationCertificate : object
    {
        
        private byte[] CertificateField;
        
        private bool SignatureValidField;
        
        private System.Nullable<System.DateTime> SignedAtField;
        
        private string SubjectField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Certificate
        {
            get
            {
                return this.CertificateField;
            }
            set
            {
                this.CertificateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool SignatureValid
        {
            get
            {
                return this.SignatureValidField;
            }
            set
            {
                this.SignatureValidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Nullable<System.DateTime> SignedAt
        {
            get
            {
                return this.SignedAtField;
            }
            set
            {
                this.SignedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Subject
        {
            get
            {
                return this.SubjectField;
            }
            set
            {
                this.SubjectField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://msign.gov.md", ConfigurationName="MSignRemoteService.IMSign")]
    public interface IMSign
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/PostSignRequest", ReplyAction="https://msign.gov.md/IMSign/PostSignRequestResponse")]
        string PostSignRequest(MSignRemoteService.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/PostSignRequest", ReplyAction="https://msign.gov.md/IMSign/PostSignRequestResponse")]
        System.Threading.Tasks.Task<string> PostSignRequestAsync(MSignRemoteService.SignRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/GetSignResponse", ReplyAction="https://msign.gov.md/IMSign/GetSignResponseResponse")]
        MSignRemoteService.SignResponse GetSignResponse(string requestID, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/GetSignResponse", ReplyAction="https://msign.gov.md/IMSign/GetSignResponseResponse")]
        System.Threading.Tasks.Task<MSignRemoteService.SignResponse> GetSignResponseAsync(string requestID, string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/VerifySignatures", ReplyAction="https://msign.gov.md/IMSign/VerifySignaturesResponse")]
        MSignRemoteService.VerificationResponse VerifySignatures(MSignRemoteService.VerificationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://msign.gov.md/IMSign/VerifySignatures", ReplyAction="https://msign.gov.md/IMSign/VerifySignaturesResponse")]
        System.Threading.Tasks.Task<MSignRemoteService.VerificationResponse> VerifySignaturesAsync(MSignRemoteService.VerificationRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMSignChannel : MSignRemoteService.IMSign, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MSignClient : System.ServiceModel.ClientBase<MSignRemoteService.IMSign>, MSignRemoteService.IMSign
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MSignClient() : 
                base(MSignClient.GetDefaultBinding(), MSignClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMSign.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSignClient(EndpointConfiguration endpointConfiguration) : 
                base(MSignClient.GetBindingForEndpoint(endpointConfiguration), MSignClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSignClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MSignClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSignClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MSignClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MSignClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string PostSignRequest(MSignRemoteService.SignRequest request)
        {
            return base.Channel.PostSignRequest(request);
        }
        
        public System.Threading.Tasks.Task<string> PostSignRequestAsync(MSignRemoteService.SignRequest request)
        {
            return base.Channel.PostSignRequestAsync(request);
        }
        
        public MSignRemoteService.SignResponse GetSignResponse(string requestID, string language)
        {
            return base.Channel.GetSignResponse(requestID, language);
        }
        
        public System.Threading.Tasks.Task<MSignRemoteService.SignResponse> GetSignResponseAsync(string requestID, string language)
        {
            return base.Channel.GetSignResponseAsync(requestID, language);
        }
        
        public MSignRemoteService.VerificationResponse VerifySignatures(MSignRemoteService.VerificationRequest request)
        {
            return base.Channel.VerifySignatures(request);
        }
        
        public System.Threading.Tasks.Task<MSignRemoteService.VerificationResponse> VerifySignaturesAsync(MSignRemoteService.VerificationRequest request)
        {
            return base.Channel.VerifySignaturesAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMSign))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMSign))
            {
                return new System.ServiceModel.EndpointAddress("https://msign.staging.egov.md:8443/MSign.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MSignClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMSign);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MSignClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMSign);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMSign,
        }
    }
}
